root.dir=C:/Users/Tudor/Desktop/facultate/year_3/FLT

ignore.extensions=.jpg,.png,.exe,.zip,.dll,.msi,.ogg,.xlsx,.o,.pdf,.docx,.lnk,.pptx,.class,.mp4,.webm,.pcap,.pkt,.md,.jar,.db,.mkv,.aac,.js

ignore.directories=.git, node_modules, obj