root.dir=C:/Users/Tudor/OneDrive - Technical University of Cluj-Napoca/Desktop/facultate/year_1/probleme_informatica

ignore.extensions=.jpg,.png,.exe,.zip,.dll,.msi,.ogg,.xslx,.o,.pdf,.docx,.lnk,.pptx

ignore.directories=.git, node_modules, obj